app = "facecard-app"  # change to your unique app name on Fly

primary_region = "sin"  # Singapore (closest to India). You can change.

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
